# Generated by Django 3.0.2 on 2020-01-27 07:28

import autoslug.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('artist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('album', models.CharField(max_length=25)),
                ('length', models.IntegerField(verbose_name='Length of Song in seconds')),
            ],
            options={
                'verbose_name': 'Favourite Songs',
                'verbose_name_plural': 'Favourite Songs',
                'ordering': ['id'],
                'unique_together': {('name', 'album')},
            },
        ),
    ]
